Dataset:
  train: Dataset/train
  valid: Dataset/valid
  test: Dataset/test
  test_weight_path: weights

  # Test
  save_flag: True
  save_path: result
  show_flag: False
  video_flag: False
  video_min: None
  video_max: None
  video_fps: 15
  video_name: video
model:
  training: False
  load_name: 128_128_ADAM_PRES18 # training = False,
  save_period: 10

  load_period: 210 # syphonic
  #load_period: 190 # waterspout

  input_size: [64, 128] # height, width
  input_frame_number: 1
  ResNetbase: 18 # resnet base version : 18, 34, 50, 101, 152
  pretrained_base: True #  input_frame_number = 1 일 때만

hyperparameters:

  # model 관련
  image_mean: [0.485, 0.456, 0.406] # R G B
  image_std:  [0.229, 0.224, 0.225] # R G B

  # 학습 관련
  epoch: 210
  batch_size: 4
  batch_log: 100
  subdivision: 1
  data_augmentation: True
  num_workers: 8 # the number of multiprocessing workers to use for data preprocessing.
  optimizer: ADAM # ADAM, RMSPROP
  learning_rate: 0.0001
  weight_decay: 0.000001
  decay_lr: 0.9
  decay_step: 1 # 몇 epoch이 지난후 decay_lr을 적용할지
context:
  using_cuda: True
validation:
  valid_size: 4
  eval_period: 10
  tensorboard: True
mlflow:
  using_mlflow: True
  run_name: classification




